<body>

<h1> Hello, Welcome to Abdulla DevOps Project !!   </h1>
<h2> Deploying on a abdulla home  </h2>
<h2> Glad to see you here </h2>
	<!--writen by abdulla next "https://www.youtube.com/watch?v=neEP0Iyx4zs&list=PLP2Oqg5TBlcpe7AuagUGHItMrPN4LxhuE&index=8" -->
	<p> <a href="index.html"> <u>Go to index Page</u> </a> </p>
 
	
	<p> <a href="https://www.facebook.com/" target="black">This is P 1 </a></P>	
		
	<p> <strong>Bangladesh</strong>, is a country in <strong>South Asia</strong>. It is the eighth-most populous country in the world, with a population exceeding 161 million people.[6][7] In terms of land mass, Bangladesh ranks 92nd, spanning 147,570 square kilometres (56,980 sq mi), making it one of the most densely-populated countries in the world. Bangladesh shares land borders with India to the west, north, and east, Myanmar to the southeast, and the Bay of Bengal to the south. It is narrowly separated from Nepal and Bhutan by India's Siliguri Corridor, and from China by the Indian state of Sikkim, in the north, respectively. Dhaka, the capital and largest city, is the nation's economic, political and cultural hub. Chittagong, the largest sea port, is the second largest city. With numerous criss-crossing rivers and inland waterways, the dominant geographic feature of Bangladesh is the Ganges delta, which empties into the Bay of Bengal with the combined waters of several river systems, including the Brahmaputra river and the Ganges river. Highlands, with evergreen forests, cover the northeastern and southeastern regions, while the country's biodiversity comprises a vast array of plants and wildlife, including the endangered Royal Bengal tiger, which is the national animal. The seacoast features the world's longest natural sandy beach in Cox's Bazar as well as the Sundarbans, which is the world's largest mangrove forest </p>
	<hr/>
	<p>Bangladesh), <em>is a country,</em> in <b>South Asia</b>. It is the eighth-most populous country in the world, with a population exceeding 161 million people.[6][7] In terms of land mass, Bangladesh ranks 92nd, spanning 147,570 square kilometres (56,980 sq mi), making it one of the most densely-populated countries in the world. Bangladesh shares land borders with India to the west, north, and east, Myanmar to the southeast, and the Bay of Bengal to the south. It is narrowly separated from Nepal and Bhutan by India's Siliguri Corridor, and from China by the Indian state of Sikkim, in the north, respectively. Dhaka, the capital and largest city, is the nation's economic, political and cultural hub. Chittagong, the largest sea port, is the second largest city. With numerous criss-crossing rivers and inland waterways, the dominant geographic feature of Bangladesh is the Ganges delta, which empties into the Bay of Bengal with the combined waters of several river systems, including the Brahmaputra river and the Ganges river. Highlands, with evergreen forests, cover the northeastern and southeastern regions, while the country's biodiversity comprises a vast array of plants and wildlife, including the endangered Royal Bengal tiger, which is the national animal. The seacoast features the world's longest natural sandy beach in Cox's Bazar as well as the Sundarbans, which is the world's largest mangrove forest </p>

	</body>